### PR TITLE
Add Tracing Spans

### PR DESCRIPTION
**Pull request by zicklag**
This can be really useful!

image

### CODE REVIEW

**Comment by gschup** [comment]
While I think this is a super cool debugging tool, putting this as a non-optional dependency seems suboptimal for users.

**Comment by gschup** [comment]
I wonder what the "correct" way of using this plugin as a library is. Do you have more experience with this? How do other libraries/plugins use this? With a feature flag?

**Comment by cscorley** [comment]
It should be possible to expose this under a feature flag using `cfg_attr`, e.g.: 

```
#[cfg_attr(feature = "trace", tracing::instrument(name = "GGRS Advance Frame", fields(frame = self.frame), skip(self, inputs, world)))]
```

In bevy_ggrs Cargo.toml, I believe something like this (taking hints from how the ["bevy/trace"](https://github.com/bevyengine/bevy/blob/main/Cargo.toml#L76) flags accomplishes this):

```
[features]
trace = [ "tracing" ]

[dependencies]
tracing = { version = "0.1.37", optional = true }
...
```

Then it should be `cargo run --features bevy_ggrs/trace` for users.

I have only done this for logging bevy systems before, but have not tested with something like Perfetto.  Seems neat :smile:


Users could also enable conditionally in their own Cargo.toml to group many together with `cargo run --features trace` 

```
[features]
default = [],
trace = [ "bevy_ggrs/trace", "bevy/trace", ... ]
```

**Comment by zicklag** [comment]
The tracing dependency is enabled by default in Bevy, and it's what powers the `info!`, `error!`, etc. logging macros.

I think the `tracing` feature in Bevy just causes bevy to emit the JSON trace files, and I don't think it actually changes what get's logged.

That's not to say that adding the tracing instrumentation to the methods doesn't add overhead, though, similar to using `info!` for logging, and I'm not sure if Bevy uses the `tracing` crate's attribute macros, so that might cause a slight increase in compile times from building the macros.

I'll take a look at how bevy does the logging for it's stages some time, because it seems like it'd be reasonable to copy how they did that, since it's essentially the same use case.

If we add the tracing spans at a low enough log level such as `debug` or `trace`, users can actually compile out any runtime cost they might have by building with the `tracing/release_max_level_info` flag, and they could do that with no effort on our part, since it's built into tracing.

---

Anyway, next step: see how Bevy does the tracing spans for their stages, and then we can probably just follow their convention, since we aren't going to be adding much extra overhead with our spans I don't think, if Bevy is already doing it for their stages.

**Comment by johanhelsing** [comment]
This is how bevy_render does it: https://github.com/bevyengine/bevy/blob/de98850a3e706a23280702e4836142917fe9bf68/crates/bevy_render/src/lib.rs#L263..L266

We could probably just do the same thing? Add a `trace` feature and create the spans inside the functions?

Not sure it the feature should be default or not, though? Might be kind of hard to discover?

**Comment by zicklag** [comment]
> We could probably just do the same thing? Add a trace feature and create the spans inside the functions?

Yeah, seems right.

It probably shouldn't be default. I guess for discoverability we'll just have to leave a note in the README and hope people find it. 🤷‍♂️

**Comment by gschup** [comment]
closed for inactivity. feel free to reopen when applicable.

**Pull request closed without merging**
