### PR TITLE
Enable desync detection in p2p example

### PR DESCRIPTION
**Pull request by johanhelsing**
This is a very useful feature, we should either enable it by default, or at least inform about it in example code.

Unfortunately, I think it's currently broken? I get desyncs as soon as the game starts without giving any input.

@HeatXD

### CODE REVIEW

**Comment by HeatXD** [comment]
Mm just tested it in the normal examples and it worked fine. i will look at this.

**Comment by HeatXD** [comment]
> 

Does bevy's worlds have some non gameplay relevant state which is included in the snapshot?

**Comment by johanhelsing** [comment]
seems they're using `AHasher::default` in bevy

**Comment by johanhelsing** [comment]
Was able to make it work with this branch: https://github.com/johanhelsing/bevy/tree/fixed-reflect-hash-0.9.1

**Comment by gschup** [comment]
very interesting! let's see how this goes :)

**Comment by johanhelsing** [comment]
Tested it in Cargo Space as well, works great!

And I had no desyncs :tada: (or at least not any for my components that implement reflect_hash)

**Comment by gschup** [comment]
is this PR still a draft?

**Comment by johanhelsing** [comment]
Did a Ggrsevent use get lost in the merge?

**Comment by johanhelsing** [comment]
Yeah, no problem! Just trying to help. Thanks for the super quick release!

**Pull request merged**
